site_name: Software Deployment Notes
site_url: https://mjwhite8119-software-notes.readthedocs.io
nav:
    - Home: 
        - index.md
        - 'Software Management':
            - PackageManagement/conda.md
            - PackageManagement/aptget.md
            - PackageManagement/pip.md
            - PackageManagement/docker.md
            - PackageManagement/git.md

        - 'OS Configuration':
            - OS/configuration.md
            - OS/linuxCommands.md
            - OS/ssh.md
            - OS/gstreamer.md
            - OS/raspberryPi.md
            - OS/jetsonNano.md
            - OS/brew.md

        - 'Machine Learning':
            - ML/opencv.md
            - ML/pytorch.md
            - ML/tensorflow.md
            - ML/depthai.md
            - ML/training.md 
            - ML/modelConversion.md

        - 'FIRST Robotics': 
            - WPI/romi.md 
            - WPI/networkTables.md  
            - WPI/vision.md

        - 'ROS': 
            - ROS/install.md  

theme: readthedocs
python:
  install:
    - requirements: requirements.txt